import { _electron as electron, expect } from 'playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import http from 'node:http';
import { createFixture } from './fixture.mjs';
const project = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const packaged = process.argv.includes('--packaged');
const output = path.join(project, 'test-results');
await fs.mkdir(output, { recursive: true });
const fixture = path.join(output, 'manual-400-pages.pdf');
await createFixture(fixture, 400);
const env = { ...process.env, RM_TEST_MODE: '1', RM_TEST_DATA: path.join(output, `profile-${Date.now()}`) };
delete env.ELECTRON_RUN_AS_NODE;
const errors = [], checks = [];
const mark = name => { checks.push(name); console.log(`PASS ${name}`); };
let app;
const server = http.createServer(async (req, res) => {
  let raw = ''; for await (const chunk of req) raw += chunk;
  const body = JSON.parse(raw);
  const input = body.messages.at(-1).content;
  if (input.includes('delayed')) await new Promise(resolve => setTimeout(resolve, 700));
  res.writeHead(200, { 'Content-Type': 'application/json' });
  res.end(JSON.stringify({ message: { content: input.includes('delayed') ? 'Bản dịch cũ không được hiển thị.' : 'Cờ ngắt được xóa bằng cách ghi 1.' } }));
});
await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
try {
  app = await electron.launch({ args: packaged ? [] : [project], ...(packaged ? { executablePath: 'E:/App_RM/release/win-unpacked/RM Reader.exe' } : {}), cwd: project, env, timeout: 60000 });
  const page = await app.firstWindow();
  page.on('pageerror', error => errors.push(error.message));
  page.on('console', message => { if (message.type() === 'error') console.log('RENDERER', message.text().slice(0, 300)); });
  await page.waitForFunction(() => !!window.rmTest, { timeout: 30000 });
  if (!packaged) await page.screenshot({ path: path.join(output, 'welcome.png') });
  mark('App boots and displays Vietnamese interface');
  await app.evaluate(({ dialog }, filename) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [filename] }); }, fixture);
  await page.click('#open-pdf');
  await expect(page.locator('#page-count')).toHaveText('400', { timeout: 30000 });
  await expect(page.locator('#loading')).toBeHidden({ timeout: 30000 });
  await page.locator('.page[data-page-number="1"] .textLayer span').first().waitFor();
  await expect(page.locator('.outline-item')).toHaveCount(3);
  mark('400-page PDF renders selectable text and nested outline');

  await page.selectOption('#zoom', '1.5');
  await page.evaluate(() => { document.getElementById('viewerContainer').scrollTop = 720; });
  await page.waitForTimeout(250);
  const origin = await page.evaluate(() => window.rmTest.capturePosition());
  const blueLink = page.locator('.page[data-page-number="1"] .linkAnnotation a');
  await blueLink.waitFor();
  const box = await blueLink.boundingBox();
  assert.ok(box && box.y > 100 && box.y < 900, 'Link must be visible before testing click');
  await page.mouse.click(box.x + box.width/2, box.y + box.height/2);
  await expect(page.locator('#page-number')).toHaveValue('300', { timeout: 15000 });
  mark('Blue internal link navigates to page 300');
  await page.keyboard.press('Alt+ArrowLeft');
  await expect(page.locator('#page-number')).toHaveValue('1');
  await page.waitForFunction(expected => window.rmTest.idle && Math.abs(window.rmTest.capturePosition().scrollTop - expected) < 2, origin.scrollTop, { timeout: 5000 }).catch(async error => {
    console.log('BACK_DIAGNOSTIC', JSON.stringify({ origin, back: await page.evaluate(() => window.rmTest.capturePosition()), history: await page.evaluate(() => window.rmTest.history) })); throw error;
  });
  const back = await page.evaluate(() => window.rmTest.capturePosition());
  assert.equal(back.scale, origin.scale); assert.ok(Math.abs(back.scrollTop - origin.scrollTop) < 2);
  mark('Back restores exact origin scroll and zoom');
  await page.keyboard.press('Alt+ArrowRight');
  await expect(page.locator('#page-number')).toHaveValue('300');
  await page.evaluate(() => window.rmTest.linkService.goToDestination('register-section'));
  await expect(page.locator('#page-number')).toHaveValue('350');
  await page.evaluate(() => window.rmTest.linkService.goToDestination([398, { name: 'XYZ' }, 0, 600, 1.25]));
  await expect(page.locator('#page-number')).toHaveValue('399');
  await page.evaluate(() => document.dispatchEvent(new MouseEvent('mouseup', { button: 3, bubbles: true, cancelable: true })));
  await expect(page.locator('#page-number')).toHaveValue('350');
  await page.click('#back'); await expect(page.locator('#page-number')).toHaveValue('300');
  await page.click('#back'); await expect(page.locator('#page-number')).toHaveValue('1');
  mark('Named destination and three-level mouse/toolbar history work');

  await page.getByRole('button', { name: '2. Peripheral registers', exact: true }).click();
  await expect(page.locator('#page-number')).toHaveValue('350');
  await page.click('#back'); await expect(page.locator('#page-number')).toHaveValue('1');
  await page.waitForFunction(() => window.rmTest.idle);
  mark('Outline jumps to destination and Back returns');

  await page.selectOption('#zoom', '1');
  await page.waitForTimeout(700);
  await page.evaluate(() => { document.getElementById('viewerContainer').scrollTop = 320; });
  await page.waitForTimeout(300);
  const selectableLink = page.locator('.page[data-page-number="1"] .textLayer span').filter({ hasText: /^See section 300/ }).first();
  await selectableLink.waitFor({ state: 'visible' });
  const selectionLinkBox = await selectableLink.boundingBox();
  await page.mouse.move(selectionLinkBox.x + 2, selectionLinkBox.y + selectionLinkBox.height / 2);
  await page.mouse.down();
  await page.mouse.move(selectionLinkBox.x + selectionLinkBox.width - 2, selectionLinkBox.y + selectionLinkBox.height / 2, { steps: 16 });
  await page.mouse.up();
  await page.waitForTimeout(250);
  assert.match(await page.evaluate(() => window.getSelection().toString()), /section/);
  await expect(page.locator('#page-number')).toHaveValue('1');
  mark('Dragging across blue linked text selects text without following link');
  await page.evaluate(() => window.getSelection().removeAllRanges());
  const term = page.locator('.page[data-page-number="1"] .textLayer span').filter({ hasText: /^interrupt$/ }).first();
  await term.waitFor({ state: 'visible', timeout: 15000 });
  const termBox = await term.boundingBox();
  await page.mouse.dblclick(termBox.x + termBox.width/2, termBox.y + termBox.height/2);
  await expect(page.locator('#selection-translate')).toBeVisible({ timeout: 5000 });
  await page.click('#selection-save');
  await expect(page.locator('#vocabulary-save-dialog')).toBeVisible();
  await page.click('#vocabulary-save-confirm');
  await expect(page.locator('#vocabulary-save-dialog')).toBeHidden();
  const untranslatedState = await page.evaluate(() => window.desktop.getState());
  assert.equal(untranslatedState.vocabulary.length, 1);
  assert.equal(untranslatedState.vocabulary[0].translation, '');
  mark('Floating selection toolbar saves vocab before translation');
  await page.click('#selection-translate');
  await expect(page.locator('#translation-result')).toHaveText('ngắt', { timeout: 10000 });
  mark('Real mouse text selection translates embedded term offline');
  await page.click('#save-translated-vocab');
  await page.click('#vocabulary-save-confirm');
  await expect(page.locator('#vocabulary-save-dialog')).toBeHidden();
  const translatedState = await page.evaluate(() => window.desktop.getState());
  assert.equal(translatedState.vocabulary.length, 1, 'Saving again updates the meaning without creating duplicate vocab');
  await page.click('#vocabulary-button');
  await expect(page.locator('.vocabulary-card')).toHaveCount(1);
  await expect(page.locator('.vocabulary-meaning')).toHaveText('ngắt');
  await page.fill('#vocabulary-filter', 'ngắt');
  await expect(page.locator('.vocabulary-card')).toHaveCount(1);
  await page.fill('#vocabulary-filter', 'unmatched-word');
  await expect(page.locator('.vocabulary-card')).toHaveCount(0);
  await page.fill('#vocabulary-filter', ''); await page.click('#vocabulary-close');
  mark('Selected vocab stores Vietnamese meaning and can be searched');

  await page.evaluate(() => window.rmTest.translate('The peripheral clock is enabled.'));
  await expect(page.locator('#translation-result')).toContainText('API key');
  assert.equal(await page.locator('#page-count').innerText(), '400');
  mark('Missing API key produces useful error while PDF stays readable');
  await page.evaluate(async endpoint => {
    await window.desktop.saveSettings({ provider: 'ollama', endpoint, model: 'test', autoTranslate: false, translationFont: 16 });
    const old = window.rmTest.translate('The delayed interrupt is enabled.');
    await new Promise(resolve => setTimeout(resolve, 80));
    await window.rmTest.translate('Write one to clear the interrupt flag.');
    await old;
  }, `http://127.0.0.1:${server.address().port}`);
  await expect(page.locator('#translation-result')).toHaveText('Cờ ngắt được xóa bằng cách ghi 1.');
  mark('Provider response works and stale translation cannot overwrite new selection');
  await page.keyboard.press('Control+f'); await page.fill('#find-input', 'volatile');
  await expect(page.locator('#find-count')).toContainText('kết quả', { timeout: 30000 });
  await page.click('#find-next');
  await expect(page.locator('#page-number')).toHaveValue('2', { timeout: 15000 });
  await page.click('#find-close'); await page.click('#back');
  await expect(page.locator('#page-number')).toHaveValue('1');
  await page.waitForFunction(() => window.rmTest.idle);
  mark('PDF search highlights results, navigates and records history');

  await page.evaluate(() => window.getSelection().removeAllRanges());
  await page.evaluate(() => window.rmTest.linkService.goToPage(120));
  await expect(page.locator('#page-number')).toHaveValue('120');
  await page.selectOption('#zoom', '1.25');
  await page.evaluate(() => { const view = window.rmTest.pdfViewer.getPageView(119).div; document.getElementById('viewerContainer').scrollTop = view.offsetTop + 333; });
  await page.waitForTimeout(700);
  const saved = await page.evaluate(() => window.rmTest.capturePosition());
  const state = await page.evaluate(() => window.desktop.getState());
  if (state.recent[0].position.page !== 120) console.log('SAVE_DIAGNOSTIC', JSON.stringify({ saved, actual: state.recent[0].position }));
  assert.equal(state.recent[0].position.page, 120);
  await page.evaluate(async id => window.rmTest.openDocument(await window.desktop.reopenPdf(id)), state.recent[0].id);
  await expect(page.locator('#page-number')).toHaveValue('120');
  const resumed = await page.evaluate(() => window.rmTest.capturePosition());
  assert.equal(resumed.scale, saved.scale); assert.ok(Math.abs(resumed.scrollTop - saved.scrollTop) < 2);
  mark('Reopening PDF restores page 120, scroll offset and zoom');
  await page.evaluate(() => window.rmTest.linkService.goToPage(300));
  await app.evaluate(({ BrowserWindow }) => { BrowserWindow.getAllWindows()[0].emit('app-command', { preventDefault() {} }, 'browser-backward'); });
  await page.waitForFunction(expected => window.rmTest.idle && Math.abs(window.rmTest.capturePosition().scrollTop - expected) < 2, saved.scrollTop);
  await expect(page.locator('#page-number')).toHaveValue('120');
  mark('Windows app-command Back routes to PDF position history');
  const secondFixture = path.join(output, 'another-manual.pdf');
  await createFixture(secondFixture, 8);
  await app.evaluate(({ dialog }, filenames) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: filenames }); }, [secondFixture, fixture]);
  await page.click('#new-tab');
  await expect(page.locator('#document-tabs [role="tab"]')).toHaveCount(3);
  await expect(page.locator('#page-number')).toHaveValue('120');
  mark('Multi-file picker opens tabs and duplicate file reuses existing tab');
  const tabIds = await page.evaluate(() => window.rmTest.tabs.map(tab => tab.id));
  await page.locator(`#tab-${tabIds[1]}`).click();
  await expect(page.locator('#page-count')).toHaveText('8');
  await page.evaluate(() => window.rmTest.linkService.goToPage(4));
  await page.selectOption('#zoom', '1.5');
  await page.waitForTimeout(250);
  const secondPosition = await page.evaluate(() => window.rmTest.capturePosition());
  await page.locator(`#tab-${tabIds[0]}`).click();
  await expect(page.locator('#page-count')).toHaveText('400');
  await expect(page.locator('#page-number')).toHaveValue('120');
  await page.waitForFunction(expected => Math.abs(window.rmTest.capturePosition().scrollTop - expected.scrollTop) < 2 && window.rmTest.capturePosition().scale === expected.scale, saved);
  await page.click('#forward'); await expect(page.locator('#page-number')).toHaveValue('300');
  await page.click('#back'); await expect(page.locator('#page-number')).toHaveValue('120');
  await page.locator(`#tab-${tabIds[1]}`).click();
  await page.waitForFunction(expected => Math.abs(window.rmTest.capturePosition().scrollTop - expected.scrollTop) < 2 && window.rmTest.capturePosition().scale === expected.scale, secondPosition);
  await page.click('#back'); await expect(page.locator('#page-number')).toHaveValue('1');
  mark('Each tab preserves independent scroll, zoom and Back/Forward history');
  await page.click('#tab-start');
  await expect(page.locator('#welcome')).toBeVisible();
  await expect(page.locator('#page-number')).toBeDisabled();
  await page.keyboard.press('Control+Tab');
  await expect(page.locator('#page-count')).toHaveText('400');
  await page.keyboard.press('Control+Tab');
  await expect(page.locator('#page-count')).toHaveText('8');
  await page.keyboard.press('Control+w');
  await expect(page.locator('#document-tabs [role="tab"]')).toHaveCount(2);
  await expect(page.locator('#page-count')).toHaveText('400');
  mark('Start tab, keyboard tab switching and closing active tab work');
  await page.click('#vocabulary-button');
  await page.locator('.vocabulary-source').click();
  await expect(page.locator('#page-number')).toHaveValue('1');
  await page.waitForFunction(() => window.rmTest.idle);
  await page.click('#back'); await expect(page.locator('#page-number')).toHaveValue('120');
  mark('Saved vocab reopens its PDF source and Back restores the reading position');
  // Switch while an AI request is in flight: a result from another tab must not appear.
  await app.evaluate(({ dialog }, filename) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [filename] }); }, secondFixture);
  await page.click('#open-pdf'); await expect(page.locator('#page-count')).toHaveText('8');
  await page.evaluate(() => { window.rmTest.translate('The delayed interrupt is enabled.'); });
  await page.locator(`#tab-${tabIds[0]}`).click();
  await page.waitForTimeout(900);
  assert.notEqual(await page.locator('#translation-result').innerText(), 'Bản dịch cũ không được hiển thị.');
  await expect(page.locator('#loading')).toBeHidden();
  await expect(page.locator('#page-count')).toHaveText('400');
  mark('Translation from an inactive tab cannot overwrite the active PDF');
  await page.evaluate(() => window.rmTest.translate('Write one to clear the interrupt flag.'));
  if (!packaged) await page.screenshot({ path: path.join(output, 'reader.png') });
  await page.click('#vocabulary-button');
  if (!packaged) await page.screenshot({ path: path.join(output, 'vocabulary.png') });
  await page.click('#vocabulary-close');
  await page.keyboard.press('Control+w'); await expect(page.locator('#page-count')).toHaveText('8');
  await page.keyboard.press('Control+w'); await expect(page.locator('#welcome')).toBeVisible();
  await expect(page.locator('#document-tabs [role="tab"]')).toHaveCount(1);
  mark('Closing all PDFs releases their tabs and returns to Start');
  assert.deepEqual(errors, [], 'Renderer must have no uncaught errors');
  await app.close(); app = null;
  app = await electron.launch({ args: packaged ? [] : [project], ...(packaged ? { executablePath: 'E:/App_RM/release/win-unpacked/RM Reader.exe' } : {}), cwd: project, env, timeout: 60000 });
  const reopenedPage = await app.firstWindow();
  await reopenedPage.waitForFunction(() => !!window.rmTest);
  await reopenedPage.click('#vocabulary-button');
  await expect(reopenedPage.locator('.vocabulary-card')).toHaveCount(1);
  await expect(reopenedPage.locator('.vocabulary-meaning')).toHaveText('ngắt');
  await reopenedPage.locator('.vocabulary-source').click();
  await expect(reopenedPage.locator('#page-count')).toHaveText('400');
  await expect(reopenedPage.locator('#page-number')).toHaveValue('1');
  await reopenedPage.click('#vocabulary-button');
  await reopenedPage.getByRole('button', { name: 'Xóa vocab interrupt', exact: true }).click();
  await expect(reopenedPage.locator('.vocabulary-card')).toHaveCount(0);
  const finalState = await reopenedPage.evaluate(() => window.desktop.getState());
  assert.equal(finalState.vocabulary.length, 0);
  mark('Vocab survives app restart, reopens a closed PDF and supports deletion');
  await reopenedPage.click('#vocabulary-close');
  await reopenedPage.locator('.switch-label').click();
  await reopenedPage.waitForFunction(async () => (await window.desktop.getState()).settings.autoTranslate);
  const autoTerm = reopenedPage.locator('.page[data-page-number="1"] .textLayer span').filter({ hasText: /^register$/ }).first();
  await autoTerm.waitFor({ state: 'visible' });
  const autoBox = await autoTerm.boundingBox();
  await reopenedPage.mouse.dblclick(autoBox.x + autoBox.width/2, autoBox.y + autoBox.height/2);
  await expect(reopenedPage.locator('#translation-result')).toHaveText('thanh ghi');
  await expect(reopenedPage.locator('#selection-save')).toBeVisible();
  await reopenedPage.click('#selection-save');
  await reopenedPage.click('#vocabulary-save-confirm');
  await expect(reopenedPage.locator('#vocabulary-save-dialog')).toBeHidden();
  const autoState = await reopenedPage.evaluate(() => window.desktop.getState());
  assert.equal(autoState.vocabulary[0].text, 'register');
  assert.equal(autoState.vocabulary[0].translation, 'thanh ghi');
  mark('Automatic translation still offers floating Save vocab and saves its meaning');
  console.log(`\n${checks.length} app checks passed.`);
  await fs.writeFile(path.join(output, 'checks.json'), JSON.stringify({ checks, errors }, null, 2));
} catch (error) {
  console.error(error);
  if (app && !packaged) { const page = await app.firstWindow(); await page.screenshot({ path: path.join(output, 'failure.png') }).catch(() => {}); }
  process.exitCode = 1;
} finally {
  await app?.close().catch(() => {});
  await new Promise(resolve => server.close(resolve));
}
