import { _electron as electron,expect } from 'playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { attachmentFixture } from './attachment-fixture.mjs';
import { createFixture } from './fixture.mjs';
const project=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),output=path.join(project,'test-results');await fs.mkdir(output,{recursive:true});
const filename=path.join(output,'attachments-manual.pdf'),embeddedFilename=path.join(output,'attachments-nested.pdf'),plain=path.join(output,'attachments-empty.pdf');
const originals=await attachmentFixture(filename,embeddedFilename);await createFixture(plain,12);
const packaged=process.argv.includes('--packaged'),profile=path.join(output,`attachments-profile-${Date.now()}`),env={...process.env,RM_TEST_MODE:'1',RM_TEST_DATA:profile};delete env.ELECTRON_RUN_AS_NODE;
const launch=()=>electron.launch({args:packaged?[]:[project],...(packaged?{executablePath:'E:/App_RM/release/win-unpacked/RM Reader.exe'}:{}),cwd:project,env,timeout:60000});
let app,page;const checks=[],errors=[];const mark=name=>{checks.push(name);console.log('PASS '+name);};
const filter=async text=>{await page.fill('#attachments-filter',text);};
try{
  app=await launch();page=await app.firstWindow();page.on('pageerror',e=>errors.push(e.message));await page.waitForFunction(()=>!!window.rmTest);
  await app.evaluate(({dialog,shell},filename)=>{globalThis.attachmentOpenCalls=[];shell.openPath=async filename=>{globalThis.attachmentOpenCalls.push(filename);return '';};dialog.showOpenDialog=async()=>({canceled:false,filePaths:[filename]});},filename);
  await page.click('#open-pdf');await expect(page.locator('#page-count')).toHaveText('8');
  const parentId=await page.evaluate(()=>window.rmTest.tabs[0].id);
  await page.click('#toggle-attachments');await expect(page.locator('.attachment-row')).toHaveCount(6,{timeout:30000});
  await expect(page.locator('#attachments-status')).not.toContainText('Đang tìm');await expect(page.locator('#outline-panel')).toBeHidden();
  if(!packaged)await page.screenshot({path:path.join(output,'attachments-sidebar.png')});
  mark('Sidebar lists named attachments and unvisited page-only attachments without duplicate page icons');
  await filter('địa chỉ GPIOA');await expect(page.locator('.attachment-row')).toHaveCount(1);await expect(page.locator('.attachment-name')).toContainText('S32K_Memory_Map.xlsx');
  mark('Filename and Vietnamese description search find a spreadsheet');
  await page.locator('.attachment-actions').getByRole('button',{name:'Mở S32K_Memory_Map.xlsx',exact:true}).click();
  await expect.poll(()=>app.evaluate(()=>globalThis.attachmentOpenCalls.length)).toBe(1);
  const opened=await app.evaluate(()=>globalThis.attachmentOpenCalls[0]);assert.deepEqual(await fs.readFile(opened),originals.workbook);assert.ok(opened.startsWith(path.join(profile,'attachments')));
  mark('Excel attachment opens through Windows association with intact bytes in the app extraction folder');
  const savedPath=path.join(output,`saved-attachment-${Date.now()}.xlsx`);
  await app.evaluate(({dialog},filePath)=>{dialog.showSaveDialog=async()=>({canceled:false,filePath});},savedPath);
  await page.getByRole('button',{name:'Lưu S32K_Memory_Map.xlsx',exact:true}).click();await expect.poll(async()=>fs.readFile(savedPath).then(b=>b.equals(originals.workbook)).catch(()=>false)).toBe(true);
  mark('Save attachment writes the exact embedded workbook to the selected location');
  await app.evaluate(({dialog})=>{dialog.showSaveDialog=async()=>({canceled:true});});await page.getByRole('button',{name:'Lưu S32K_Memory_Map.xlsx',exact:true}).click();
  await expect(page.locator('#attachments-save-all')).toBeEnabled();
  mark('Canceling Save leaves the document and sidebar usable');
  await filter('script.cmd');await expect(page.getByRole('button',{name:'Mở script.cmd',exact:true})).toBeDisabled();
  const beforeCalls=await app.evaluate(()=>globalThis.attachmentOpenCalls.length);
  const blocked=await page.evaluate(async()=>{try{await window.desktop.openAttachment({token:window.rmReader.attachmentSource.info.token,name:'script.cmd',content:new Uint8Array([1,2])});return false;}catch{return true;}});assert.equal(blocked,true);assert.equal(await app.evaluate(()=>globalThis.attachmentOpenCalls.length),beforeCalls);
  mark('Executable attachments support Save and cannot launch through the backend');
  const folder=path.join(output,`saved-attachments-${Date.now()}`);await fs.mkdir(folder);await fs.writeFile(path.join(folder,'S32K_Memory_Map.xlsx'),'existing file');
  await app.evaluate(({dialog},folder)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[folder]});},folder);
  await page.click('#attachments-save-all');await expect.poll(async()=>(await fs.readdir(folder)).length).toBe(7);
  assert.equal(await fs.readFile(path.join(folder,'S32K_Memory_Map.xlsx'),'utf8'),'existing file');assert.deepEqual(await fs.readFile(path.join(folder,'S32K_Memory_Map (1).xlsx')),originals.workbook);assert.deepEqual(await fs.readFile(path.join(folder,'S32K_Memory_Map (2).xlsx')),originals.workbook);assert.deepEqual(await fs.readFile(path.join(folder,'Page_note.txt')),originals.pageBytes);assert.equal((await fs.stat(path.join(folder,'empty.txt'))).size,0);
  mark('Save all includes all files regardless of search, sanitizes embedded paths and preserves existing filenames');
  await filter('nested');await page.getByRole('button',{name:'Mở nested-datasheet.pdf',exact:true}).click();await expect(page.locator('#page-count')).toHaveText('10');
  assert.equal((await page.evaluate(()=>window.rmTest.tabs)).length,2);await expect(page.locator('#attachments-source')).toHaveText('nested-datasheet.pdf');
  mark('Embedded PDF opens inside a new app tab and the sidebar follows the active document');
  await page.evaluate(id=>window.rmTest.activateTab(id),parentId);await filter('nested');await page.getByRole('button',{name:'Mở nested-datasheet.pdf',exact:true}).click();assert.equal((await page.evaluate(()=>window.rmTest.tabs)).length,2);
  mark('Opening the same embedded PDF reuses a stable extracted file and existing tab');
  await page.evaluate(id=>window.rmTest.activateTab(id),parentId);await page.click('#attachments-close');await expect(page.locator('#outline-panel')).toBeVisible();
  await page.selectOption('#zoom','1');await page.locator('.page[data-page-number="1"] .fileAttachmentAnnotation').first().dblclick();await expect(page.locator('#page-count')).toHaveText('10');
  mark('Double-clicking a real paperclip annotation opens the embedded PDF through the same tab workflow');
  await app.evaluate(({dialog},filename)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[filename]});},plain);await page.click('#open-pdf');await expect(page.locator('#page-count')).toHaveText('12');await page.click('#toggle-attachments');await expect(page.locator('#attachments-list')).toContainText('không có tệp đính kèm',{timeout:30000});
  mark('PDFs without attachments show a clear empty state');
  await page.click('#compare-button');await page.waitForFunction(()=>!!document.getElementById('comparison-frame').contentWindow?.rmReader?.document);
  const right=page.frames().find(f=>f.url().includes('pane=right'));
  await right.evaluate(async id=>{await window.rmReader.openDocument(await window.parent.desktop.reopenPdf(id));},parentId);
  await right.click('#toggle-attachments');await expect(page.locator('#attachments-source')).toHaveText('attachments-manual.pdf');await filter('địa chỉ');await page.getByRole('button',{name:'Mở S32K_Memory_Map.xlsx',exact:true}).click();
  await expect.poll(()=>app.evaluate(()=>globalThis.attachmentOpenCalls.length)).toBe(2);await expect(page.locator('#page-count')).toHaveText('12');
  mark('The shared attachment sidebar reads the focused right PDF without changing the left document');
  await filter('nested');await page.getByRole('button',{name:'Mở nested-datasheet.pdf',exact:true}).click();await expect(right.locator('#page-count')).toHaveText('10');await expect(page.locator('#page-count')).toHaveText('12');
  mark('A right-pane PDF attachment opens into the right pane independently');
  assert.deepEqual(errors,[]);await fs.writeFile(path.join(output,'attachments-checks.json'),JSON.stringify({checks,errors,packaged},null,2));console.log(`${checks.length} attachment checks passed.`);
}catch(error){console.error(error);if(page && !packaged)await page.screenshot({path:path.join(output,'attachments-failure.png')}).catch(()=>{});process.exitCode=1;}
finally{await app?.close().catch(()=>{});}
