import { _electron as electron, expect } from 'playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createFixture } from './fixture.mjs';
const project = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const output = path.join(project, 'test-results'); await fs.mkdir(output, { recursive: true });
const manual = path.join(output, 'compare-manual.pdf'), datasheet = path.join(output, 'compare-datasheet.pdf');
await createFixture(manual, 8); await createFixture(datasheet, 12);
const packaged = process.argv.includes('--packaged');
const env = { ...process.env, RM_TEST_MODE: '1', RM_TEST_DATA: path.join(output, `notes-profile-${Date.now()}`) }; delete env.ELECTRON_RUN_AS_NODE;
const launch = () => electron.launch({ args: packaged ? [] : [project], ...(packaged ? { executablePath: 'E:/App_RM/release/win-unpacked/RM Reader.exe' } : {}), cwd: project, env, timeout: 60000 });
const checks = [], errors = []; const mark = name => { checks.push(name); console.log('PASS ' + name); }; let app;
try {
  app = await launch(); let page = await app.firstWindow(); page.on('pageerror', error => errors.push(error.message));
  await page.waitForFunction(() => !!window.rmTest);
  await app.evaluate(({ dialog }, filenames) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: filenames }); }, [manual, datasheet]);
  await page.click('#open-pdf'); await expect(page.locator('#page-count')).toHaveText('12');
  const firstId = await page.evaluate(() => window.rmTest.tabs[0].id);
  const otherId = await page.evaluate(() => window.rmTest.tabs[1].id);
  await page.evaluate(id => window.rmTest.activateTab(id), firstId);
  const sourceTab = page.locator(`#tab-${firstId}`).locator('..'), targetTab = page.locator(`#tab-${otherId}`).locator('..');
  await sourceTab.dragTo(targetTab, { targetPosition: { x: 170, y: 16 } });
  assert.deepEqual(await page.evaluate(() => window.rmTest.tabs.map(tab => tab.id)), [otherId, firstId]);
  await expect(page.locator(`#tab-${firstId}`)).toHaveAttribute('aria-selected', 'true');
  mark('Dragging PDF tabs changes their order while retaining the active document');
  await page.locator(`#tab-${firstId}`).focus(); await page.keyboard.press('Control+Shift+ArrowLeft');
  assert.deepEqual(await page.evaluate(() => window.rmTest.tabs.map(tab => tab.id)), [firstId, otherId]);
  mark('Keyboard tab reordering supports the same stable document state');
  await page.click('#compare-button');
  await page.waitForFunction(() => document.getElementById('comparison-frame').contentWindow?.rmReader?.document, { timeout: 20000 });
  const right = page.frames().find(frame => frame.url().includes('pane=right'));
  assert.ok(right); await expect(right.locator('#page-count')).toHaveText('12');
  await expect(page.locator('#page-count')).toHaveText('8');
  mark('Two local PDF panes render distinct files through the existing safe IPC bridge');
  await page.selectOption('#zoom', '1'); await page.evaluate(() => window.rmTest.linkService.goToPage(4));
  const leftBefore = await page.evaluate(() => window.rmTest.capturePosition());
  await right.evaluate(() => window.rmTest.linkService.goToPage(6)); await right.selectOption('#zoom', '1.5');
  await right.locator('#viewerContainer').focus();
  const rightBox = await right.locator('#viewerContainer').boundingBox();
  await page.mouse.move(rightBox.x + rightBox.width / 2, rightBox.y + rightBox.height / 2); await page.mouse.wheel(0, 280); await page.waitForTimeout(350);
  const leftAfter = await page.evaluate(() => window.rmTest.capturePosition());
  assert.equal(leftAfter.page, leftBefore.page); assert.equal(leftAfter.scale, leftBefore.scale); assert.ok(Math.abs(leftAfter.scrollTop - leftBefore.scrollTop) < 2);
  assert.equal((await right.evaluate(() => window.rmTest.capturePosition())).scale, 1.5);
  mark('Right pane scrolling and zoom do not move or zoom the left PDF');
  await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].emit('app-command', { preventDefault() {} }, 'browser-backward'));
  await expect(right.locator('#page-number')).toHaveValue('1'); await expect(page.locator('#page-number')).toHaveValue('4');
  mark('Mouse Back follows the focused pane and keeps independent histories');
  await page.evaluate(() => window.rmTest.linkService.goToPage(1)); await page.selectOption('#zoom', '1');
  await page.evaluate(() => { document.getElementById('viewerContainer').scrollTop = 320; });
  const term = page.locator('.page[data-page-number="1"] .textLayer span').filter({ hasText: /^interrupt$/ }).first();
  await term.waitFor({ state: 'visible' }); const termBox = await term.boundingBox();
  await page.mouse.dblclick(termBox.x + termBox.width / 2, termBox.y + termBox.height / 2);
  await expect(page.locator('#selection-note')).toBeVisible(); await page.click('#selection-note');
  await page.check('input[name="annotation-color"][value="pink"]'); await page.fill('#annotation-note', 'Chú ý bit này phải ghi 1 để xóa.'); await page.click('#annotation-save');
  await expect(page.locator('#annotation-dialog')).toBeHidden(); await expect(page.locator('.saved-highlight.mark-pink').first()).toBeVisible();
  let state = await page.evaluate(() => window.desktop.getState()); assert.equal(state.annotations.length, 1); const entry = state.annotations[0];
  assert.equal(entry.documentId, firstId); assert.equal(entry.color, 'pink'); assert.equal(entry.text, 'interrupt');
  mark('Real text selection creates a colored mark and note at the exact source');
  await page.selectOption('#zoom', '1.5');
  await page.waitForFunction(entry => {
    const view = window.rmTest.pdfViewer.getPageView(0), mark = view.div.querySelector('.saved-highlight');
    if (!mark) return false; const rect = entry.rects[0].rect; const [x1, y1, x2, y2] = [...view.viewport.convertToViewportPoint(rect[0], rect[1]), ...view.viewport.convertToViewportPoint(rect[2], rect[3])];
    return Math.abs(parseFloat(mark.style.left) - Math.min(x1, x2)) < 1 && Math.abs(parseFloat(mark.style.width) - Math.abs(x2 - x1)) < 1;
  }, entry);
  mark('Highlight stays aligned after zoom by restoring PDF coordinates');
  await page.locator('.annotation-marker').first().click(); await page.check('input[name="annotation-color"][value="blue"]');
  await page.fill('#annotation-note', 'Ghi 1 để xóa cờ ngắt; không ghi 0.'); await page.click('#annotation-save');
  await expect(page.locator('.saved-highlight.mark-blue').first()).toBeVisible();
  mark('Inline note marker opens the editor and supports changing color and text');
  await right.selectOption('#zoom', '1'); await right.evaluate(() => { document.getElementById('viewerContainer').scrollTop = 320; });
  const rightTerm = right.locator('.page[data-page-number="1"] .textLayer span').filter({ hasText: /^register$/ }).first();
  await rightTerm.waitFor({ state: 'visible' }); const rb = await rightTerm.boundingBox();
  await page.mouse.dblclick(rb.x + rb.width / 2, rb.y + rb.height / 2); await expect(right.locator('#selection-note')).toBeVisible(); await right.click('#selection-note');
  await expect(page.locator('#annotation-dialog')).toBeVisible(); await page.fill('#annotation-note', 'Đối chiếu thông số thanh ghi với datasheet.'); await page.click('#annotation-save');
  await expect(right.locator('.saved-highlight').first()).toBeVisible();
  state = await page.evaluate(() => window.desktop.getState()); assert.equal(state.annotations.length, 2); assert.notEqual(state.annotations[0].documentId, firstId);
  mark('Selections in the right PDF save notes to that PDF and repaint both panes');
  // Shared translation/vocab must retain the right-hand document as source.
  await right.evaluate(() => window.rmTest.translate('register')); await expect(page.locator('#translation-result')).toHaveText('thanh ghi');
  await page.click('#save-translated-vocab'); await expect(page.locator('#vocabulary-save-dialog')).toBeVisible(); await page.click('#vocabulary-save-confirm'); await expect(page.locator('#vocabulary-save-dialog')).toBeHidden(); const vocab = (await page.evaluate(() => window.desktop.getState())).vocabulary[0];
  assert.equal(vocab.documentId, state.annotations[0].documentId); assert.equal(vocab.translation, 'thanh ghi');
  mark('Right pane translation uses the shared Vietnamese panel and saves the correct vocab source');
  await page.click('#translation-close');
  await page.evaluate(() => window.rmTest.linkService.goToPage(5)); await right.evaluate(() => window.rmTest.linkService.goToPage(7));
  await page.click('#annotations-button'); await page.fill('#annotations-filter', 'không ghi 0'); await expect(page.locator('.annotation-card')).toHaveCount(1);
  await page.locator('.annotation-jump').click(); await expect(page.locator('#page-number')).toHaveValue('1'); await expect(right.locator('#page-number')).toHaveValue('7');
  await page.click('#back'); await expect(page.locator('#page-number')).toHaveValue('5');
  mark('Note search and click return to its marked line with Back preserving the reading position');
  await page.locator('.page[data-page-number="5"] .textLayer span').first().waitFor();
  await page.evaluate(() => {
    const spans = [...window.rmTest.pdfViewer.getPageView(4).div.querySelectorAll('.textLayer span')];
    const first = spans.find(node => node.textContent.startsWith('The interrupt flag'));
    const last = spans.find(node => node.textContent.startsWith('GPIOA and'));
    const range = document.createRange(); range.setStart(first.firstChild, 0); range.setEnd(last.firstChild, last.firstChild.textContent.length);
    const selection = window.getSelection(); selection.removeAllRanges(); selection.addRange(range);
  });
  await expect(page.locator('#selection-translate')).toBeVisible(); await page.click('#selection-translate');
  await expect(page.locator('#translation-source')).toContainText('GPIOA');
  assert.ok((await page.locator('#translation-source').innerText()).split('\n').length >= 3);
  await page.click('#translation-close');
  mark('Selected PDF lines retain their original line breaks in the Vietnamese panel source');
  await page.click('#annotations-button'); await page.fill('#annotations-filter', ''); await page.click('#annotations-close');
  if (!packaged) { await page.screenshot({ path: path.join(output, 'comparison.png') }); await page.click('#annotations-button'); await page.screenshot({ path: path.join(output, 'annotations.png') }); await page.click('#annotations-close'); }
  await page.click('#compare-button'); await expect(page.locator('#comparison-pane')).toBeHidden(); await expect(page.locator('#primary-controls')).toBeVisible();
  await page.click('#compare-button'); await expect(right.locator('#page-number')).toHaveValue('7');
  mark('Leaving and reopening comparison preserves the right PDF and its position');
  assert.deepEqual(errors, []);
  await app.close(); app = await launch(); page = await app.firstWindow(); await page.waitForFunction(() => !!window.rmTest);
  state = await page.evaluate(() => window.desktop.getState()); assert.equal(state.annotations.length, 2); assert.equal(state.vocabulary[0].translation, 'thanh ghi');
  await page.click('#annotations-button'); await page.fill('#annotations-filter', 'không ghi 0'); await page.locator('.annotation-jump').click();
  await expect(page.locator('#page-count')).toHaveText('8'); await expect(page.locator('.saved-highlight.mark-blue').first()).toBeVisible();
  mark('Notes and highlights survive restart and reopen a closed source PDF');
  await page.click('#annotations-button'); await page.fill('#annotations-filter', 'không ghi 0'); await page.locator('.annotation-card .icon-button').click();
  await expect(page.locator('.annotation-card')).toHaveCount(0); await page.click('#annotations-close'); await expect(page.locator('.saved-highlight')).toHaveCount(0);
  mark('Deleting a note removes its stored entry and PDF highlight');
  console.log(`${checks.length} comparison/annotation checks passed.`);
  await fs.writeFile(path.join(output, 'compare-notes-checks.json'), JSON.stringify({ checks, errors, packaged }, null, 2));
} catch (error) { console.error(error); if (!packaged && app) await (await app.firstWindow()).screenshot({ path: path.join(output, 'compare-notes-failure.png') }).catch(() => {}); process.exitCode = 1; }
finally { await app?.close().catch(() => {}); }
