import { _electron as electron, expect } from 'playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createFixture } from './fixture.mjs';
const project=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),output=path.join(project,'test-results');
await fs.mkdir(output,{recursive:true});
const manual=path.join(output,'markup-manual.pdf'),sheet=path.join(output,'markup-datasheet.pdf');
await createFixture(manual,8);await createFixture(sheet,10);
const packaged=process.argv.includes('--packaged'),env={...process.env,RM_TEST_MODE:'1',RM_TEST_DATA:path.join(output,`markup-profile-${Date.now()}`)};delete env.ELECTRON_RUN_AS_NODE;
const launch=()=>electron.launch({args:packaged?[]:[project],...(packaged?{executablePath:'E:/App_RM/release/win-unpacked/RM Reader.exe'}:{}),cwd:project,env,timeout:60000});
const checks=[],errors=[];const mark=name=>{checks.push(name);console.log('PASS '+name);};let app,page;
const state=()=>page.evaluate(()=>window.desktop.getState());
const selectTerm=async(frame,word)=>{const term=frame.locator('.page[data-page-number="1"] .textLayer span').filter({hasText:new RegExp(`^${word}$`)}).first();await term.scrollIntoViewIfNeeded();const b=await term.boundingBox();await page.mouse.dblclick(b.x+b.width/2,b.y+b.height/2);};
const pagePoint=async(frame,x,y)=>frame.evaluate(([x,y])=>{const v=window.rmTest.pdfViewer.getPageView(0),b=v.div.getBoundingClientRect(),f=window.frameElement?.getBoundingClientRect();return{x:(f?.left||0)+b.left+x*v.viewport.scale,y:(f?.top||0)+b.top+y*v.viewport.scale};},[x,y]);
const stroke=async(frame,x,y,endX,endY)=>{const a=await pagePoint(frame,x,y),b=await pagePoint(frame,endX,endY);await page.mouse.move(a.x,a.y);await page.mouse.down();await page.mouse.move(b.x,b.y,{steps:12});await page.mouse.up();};
try{
  app=await launch();page=await app.firstWindow();page.on('pageerror',e=>errors.push(e.message));await page.waitForFunction(()=>!!window.rmTest);
  await app.evaluate(({dialog},filenames)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:filenames});},[manual,sheet]);
  await page.click('#open-pdf');await expect(page.locator('#page-count')).toHaveText('10');
  const id=await page.evaluate(()=>window.rmTest.tabs[0].id);await page.evaluate(id=>window.rmTest.activateTab(id),id);
  await page.selectOption('#zoom','1');await page.click('#translation-close');await page.click('#outline-close');
  await page.evaluate(()=>{document.getElementById('viewerContainer').scrollTop=300;});
  await page.click('#tool-highlight');await page.selectOption('#tool-highlight-color','green');
  await selectTerm(page,'interrupt');await expect.poll(async()=>(await state()).annotations.length).toBe(1);
  await selectTerm(page,'register');await expect.poll(async()=>(await state()).annotations.length).toBe(2);
  assert.ok((await state()).annotations.every(a=>a.color==='green'));await expect(page.locator('#annotation-dialog')).toBeHidden();await expect(page.locator('#selection-tools')).toBeHidden();
  mark('Continuous highlighting saves each real text selection without translation or a dialog');
  await page.keyboard.press('Escape');await expect(page.locator('#tool-select')).toHaveAttribute('aria-pressed','true');
  await selectTerm(page,'clock');await expect(page.locator('#selection-translate')).toBeVisible();
  mark('Escape returns to normal selection and translation');
  await page.click('#tool-draw');await page.locator('#tool-color').fill('#2457d6');await page.selectOption('#tool-width','8');
  await stroke(page,60,580,300,580);await expect.poll(async()=>(await state()).annotations.length).toBe(3);
  let ink=(await state()).annotations.find(a=>a.kind==='ink');assert.equal(ink.color,'#2457d6');assert.equal(ink.width,8);
  await expect(page.locator('.saved-ink path')).toHaveAttribute('stroke','#2457d6');
  const inkBounds=await page.locator('.saved-ink').boundingBox();assert.ok(inkBounds.width>500 && inkBounds.height>500);
  mark('Pen color and thickness are saved with a real freehand stroke');
  await page.click('#tool-erase');await stroke(page,180,560,180,600);
  await expect.poll(async()=>{const a=(await state()).annotations.find(a=>a.id===ink.id);return a?.paths.length;}).toBe(2);
  ink=(await state()).annotations.find(a=>a.id===ink.id);assert.ok(ink.paths[0].at(-1)[0]<180 && ink.paths[1][0][0]>180);
  mark('Eraser cuts the middle of an ink stroke and preserves both remaining sides');
  const highlighted=(await state()).annotations.find(a=>a.text==='interrupt'),rect=highlighted.rects[0].rect;
  const midpoint=await page.evaluate(rect=>{const v=window.rmTest.pdfViewer.getPageView(0),b=v.div.getBoundingClientRect(),p=v.viewport.convertToViewportPoint((rect[0]+rect[2])/2,(rect[1]+rect[3])/2);return{x:b.left+p[0],y:b.top+p[1]};},rect);
  await page.selectOption('#tool-eraser-size','12');await page.mouse.click(midpoint.x,midpoint.y);
  await expect.poll(async()=>(await state()).annotations.find(a=>a.id===highlighted.id)?.rects.length).toBeGreaterThan(1);
  assert.ok((await state()).annotations.some(a=>a.text==='register'));
  mark('A small eraser removes only a selected highlight region while preserving nearby marks');
  await page.click('#tool-textbox');await page.locator('#tool-color').fill('#126c4b');await page.selectOption('#tool-font-size','20');
  const p=await pagePoint(page,65,650);await page.mouse.click(p.x,p.y);await expect(page.locator('.textbox-input')).toBeVisible();
  await page.fill('.textbox-input','Chú ý: ghi 1 để xóa\nKhông ghi 0.');await page.keyboard.press('Control+Enter');
  await expect(page.locator('.saved-textbox')).toHaveText('Chú ý: ghi 1 để xóa\nKhông ghi 0.');
  let box=(await state()).annotations.find(a=>a.kind==='textbox');assert.equal(box.fontSize,20);assert.equal(box.color,'#126c4b');
  mark('Clicking Text box creates a multiline editable box at the clicked PDF position');
  await page.click('#tool-select');await page.click('.saved-textbox');await page.fill('.textbox-input','Ghi 1 để xóa cờ ngắt.');await page.click('#tool-draw');
  await expect(page.locator('.saved-textbox')).toHaveText('Ghi 1 để xóa cờ ngắt.');
  mark('Existing text boxes edit inline and save when focus leaves the box');
  await page.selectOption('#zoom','1.5');
  await page.waitForFunction(()=>{const v=window.rmTest.pdfViewer.getPageView(0),s=v.div.querySelector('.saved-ink path');return Number(s?.getAttribute('stroke-width'))===8*v.viewport.scale;});
  const font=await page.evaluate(()=>20*window.rmTest.pdfViewer.getPageView(0).viewport.scale);await expect(page.locator('.saved-textbox')).toHaveCSS('font-size',`${font}px`);
  mark('PDF-coordinate ink and text boxes scale correctly after zoom');
  await page.click('#compare-button');await page.waitForFunction(()=>!!document.getElementById('comparison-frame').contentWindow?.rmReader?.document);
  const right=page.frames().find(f=>f.url().includes('pane=right'));await right.selectOption('#zoom','1');await right.evaluate(()=>{document.getElementById('viewerContainer').scrollTop=300;});
  await right.click('#tool-draw');await right.locator('#tool-color').fill('#cc3081');await stroke(right,100,580,260,580);
  await expect.poll(async()=>(await state()).annotations.filter(a=>a.kind==='ink').length).toBe(2);
  const rightInk=(await state()).annotations.find(a=>a.color==='#cc3081');assert.notEqual(rightInk.documentId,id);
  await expect(right.locator('.saved-ink path')).toHaveAttribute('stroke','#cc3081');
  mark('Each PDF pane has independent tools and drawings belong to the correct file');
  await page.click('#annotations-button');await page.fill('#annotations-filter','ghi 1');await expect(page.locator('.annotation-card')).toHaveCount(1);await page.locator('.annotation-jump').click();
  await expect(page.locator('#page-number')).toHaveValue('1');
  mark('Text boxes appear in note search and jump to their original PDF location');
  if(!packaged)await page.screenshot({path:path.join(output,'markup-tools.png')});
  const before=(await state()).annotations;assert.deepEqual(errors,[]);
  await app.close();app=await launch();page=await app.firstWindow();await page.waitForFunction(()=>!!window.rmTest);
  assert.deepEqual((await state()).annotations,before);
  await page.click('#annotations-button');await page.fill('#annotations-filter','ghi 1');await page.locator('.annotation-jump').click();
  await expect(page.locator('.saved-textbox')).toHaveText('Ghi 1 để xóa cờ ngắt.');await expect(page.locator('.saved-ink path')).toHaveCount(2);
  mark('Highlights, partially erased strokes and text boxes survive a full app restart');
  await page.click('.saved-textbox');await page.getByRole('button',{name:'Xóa text box',exact:true}).click();await expect(page.locator('.saved-textbox')).toHaveCount(0);
  assert.ok(!(await state()).annotations.some(a=>a.id===box.id));
  mark('Text box delete removes its overlay and stored annotation');
  console.log(`${checks.length} markup checks passed.`);await fs.writeFile(path.join(output,'markup-checks.json'),JSON.stringify({checks,errors,packaged},null,2));
}catch(error){console.error(error);if(!packaged && page)await page.screenshot({path:path.join(output,'markup-failure.png')}).catch(()=>{});process.exitCode=1;}
finally{await app?.close().catch(()=>{});}
