const { contextBridge, ipcRenderer, webUtils } = require('electron');
contextBridge.exposeInMainWorld('desktop', {
  openPdf: () => ipcRenderer.invoke('pdf:open'),
  openPdfs: () => ipcRenderer.invoke('pdf:open-many'),
  openDroppedPdf: file => ipcRenderer.invoke('pdf:drop', webUtils.getPathForFile(file)),
  reopenPdf: id => ipcRenderer.invoke('pdf:reopen', id),
  releasePdf: id => ipcRenderer.invoke('pdf:release', id),
  openAttachment: input => ipcRenderer.invoke('attachments:open', input),
  saveAttachment: input => ipcRenderer.invoke('attachments:save', input),
  saveAllAttachments: inputs => ipcRenderer.invoke('attachments:save-all', inputs),
  getState: () => ipcRenderer.invoke('state:get'),
  listChats:()=>ipcRenderer.invoke('chat:list'),
  createChat:input=>ipcRenderer.invoke('chat:create',input),
  renameChat:input=>ipcRenderer.invoke('chat:rename',input),
  deleteChat:id=>ipcRenderer.invoke('chat:delete',id),
  openChatSource:input=>ipcRenderer.invoke('chat:source',input),
  sendChat:input=>ipcRenderer.invoke('chat:send',input),
  addChatImage:input=>ipcRenderer.invoke('chat:image-add',input),
  removeChatImage:id=>ipcRenderer.invoke('chat:image-remove',id),
  cancelChat:id=>ipcRenderer.invoke('chat:cancel',id),
  onChatEvent:callback=>{const fn=(_event,event)=>callback(event);ipcRenderer.on('chat:event',fn);return()=>ipcRenderer.removeListener('chat:event',fn);},
  savePosition: (id, position) => ipcRenderer.invoke('state:position', { id, position }),
  saveSettings: settings => ipcRenderer.invoke('settings:save', settings),
  saveVocabulary: entry => ipcRenderer.invoke('vocabulary:save', entry),
  deleteVocabulary: id => ipcRenderer.invoke('vocabulary:delete', id),
  openVocabulary: id => ipcRenderer.invoke('vocabulary:open', id),
  saveAnnotation: entry => ipcRenderer.invoke('annotations:save', entry),
  eraseAnnotations: input => ipcRenderer.invoke('annotations:erase', input),
  deleteAnnotation: id => ipcRenderer.invoke('annotations:delete', id),
  openAnnotation: id => ipcRenderer.invoke('annotations:open', id),
  translate: request => ipcRenderer.invoke('translate', request),
  cancelTranslation: id => ipcRenderer.send('translate:cancel', id),
  onTranslationProgress: callback => { const fn = (_event, progress) => callback(progress); ipcRenderer.on('translate:progress', fn); return () => ipcRenderer.removeListener('translate:progress', fn); },
  openExternal: url => ipcRenderer.invoke('external:open', url),
  onNavigate: callback => { const fn = (_event, action) => callback(action); ipcRenderer.on('navigate', fn); return () => ipcRenderer.removeListener('navigate', fn); }
});
