export const glossary = {
  'register': 'thanh ghi',
  'registers': 'các thanh ghi',
  'interrupt': 'ngắt',
  'interrupts': 'các ngắt',
  'interrupt service routine': 'trình phục vụ ngắt (ISR)',
  'interrupt vector': 'vectơ ngắt',
  'interrupt vector table': 'bảng vectơ ngắt',
  'interrupt priority': 'độ ưu tiên ngắt',
  'nested interrupt': 'ngắt lồng nhau',
  'peripheral': 'ngoại vi',
  'peripherals': 'các ngoại vi',
  'memory': 'bộ nhớ',
  'memory map': 'bản đồ bộ nhớ',
  'memory mapped': 'được ánh xạ vào không gian bộ nhớ',
  'memory-mapped': 'được ánh xạ vào không gian bộ nhớ',
  'memory-mapped io': 'vào/ra ánh xạ bộ nhớ',
  'volatile': 'volatile — truy cập trực tiếp giá trị có thể thay đổi ngoài luồng chương trình; thường dùng với thanh ghi ngoại vi',
  'clock': 'xung nhịp',
  'clock source': 'nguồn xung nhịp',
  'clock gating': 'đóng/mở cấp xung nhịp',
  'clock tree': 'cây phân phối xung nhịp',
  'prescaler': 'bộ chia tần số trước',
  'divider': 'bộ chia tần số',
  'timer': 'bộ định thời',
  'counter': 'bộ đếm',
  'watchdog': 'bộ giám sát watchdog',
  'watchdog timer': 'bộ định thời giám sát (watchdog)',
  'pull-up': 'kéo lên mức cao (pull-up)',
  'pull-down': 'kéo xuống mức thấp (pull-down)',
  'open-drain': 'ngõ ra cực máng hở (open-drain)',
  'push-pull': 'ngõ ra đẩy-kéo (push-pull)',
  'alternate function': 'chức năng thay thế của chân',
  'rising edge': 'sườn lên',
  'falling edge': 'sườn xuống',
  'edge triggered': 'kích hoạt theo sườn',
  'level triggered': 'kích hoạt theo mức',
  'trigger': 'tín hiệu kích hoạt',
  'flag': 'cờ trạng thái',
  'status flag': 'cờ trạng thái',
  'clear': 'xóa; với bit/cờ thường là đưa về 0',
  'set': 'thiết lập; với bit/cờ thường là đưa lên 1',
  'reset': 'đặt lại (reset)',
  'reserved': 'dành riêng (reserved)',
  'read-only': 'chỉ đọc',
  'write-only': 'chỉ ghi',
  'read/write': 'đọc/ghi',
  'write one to clear': 'ghi 1 để xóa bit/cờ (W1C)',
  'read modify write': 'đọc–sửa–ghi',
  'read-modify-write': 'đọc–sửa–ghi',
  'bit field': 'trường bit',
  'bitfield': 'trường bit',
  'bit mask': 'mặt nạ bit',
  'bus': 'bus truyền dữ liệu',
  'bus arbitration': 'phân xử quyền sử dụng bus',
  'latency': 'độ trễ',
  'throughput': 'thông lượng',
  'polling': 'thăm dò trạng thái (polling)',
  'debounce': 'chống dội tín hiệu',
  'buffer': 'bộ đệm',
  'fifo': 'FIFO — bộ đệm vào trước, ra trước',
  'dma': 'DMA — truy cập bộ nhớ trực tiếp',
  'gpio': 'GPIO — vào/ra đa dụng',
  'uart': 'UART — bộ thu phát nối tiếp bất đồng bộ',
  'usart': 'USART — bộ thu phát nối tiếp đồng bộ/bất đồng bộ',
  'spi': 'SPI — giao tiếp ngoại vi nối tiếp',
  'i2c': 'I2C — giao tiếp nối tiếp hai dây',
  'adc': 'ADC — bộ chuyển đổi tương tự sang số',
  'dac': 'DAC — bộ chuyển đổi số sang tương tự',
  'pwm': 'PWM — điều chế độ rộng xung',
  'duty cycle': 'hệ số lấp đầy (duty cycle)',
  'baud rate': 'tốc độ baud',
  'sampling rate': 'tần số lấy mẫu',
  'sample and hold': 'lấy mẫu và giữ',
  'input capture': 'bắt giá trị bộ đếm theo tín hiệu đầu vào',
  'output compare': 'so sánh giá trị bộ đếm để điều khiển đầu ra',
  'overflow': 'tràn',
  'underflow': 'tràn dưới',
  'overrun': 'tràn do dữ liệu mới đến trước khi dữ liệu cũ được xử lý',
  'endianness': 'thứ tự byte',
  'little-endian': 'thứ tự byte thấp trước (little-endian)',
  'big-endian': 'thứ tự byte cao trước (big-endian)',
  'stack': 'ngăn xếp',
  'stack pointer': 'con trỏ ngăn xếp',
  'heap': 'vùng nhớ cấp phát động (heap)',
  'bootloader': 'chương trình nạp khởi động (bootloader)',
  'firmware': 'phần mềm nhúng (firmware)',
  'flash memory': 'bộ nhớ Flash',
  'non-volatile memory': 'bộ nhớ không mất dữ liệu khi mất nguồn',
  'brown-out reset': 'reset do sụt áp nguồn (BOR)',
  'power-on reset': 'reset khi cấp nguồn (POR)',
  'low-power mode': 'chế độ tiết kiệm năng lượng',
  'sleep mode': 'chế độ ngủ',
  'wake-up': 'đánh thức',
  'real-time': 'thời gian thực',
  'rtos': 'RTOS — hệ điều hành thời gian thực',
  'semaphore': 'semaphore — cơ chế đồng bộ/đếm tài nguyên',
  'mutex': 'mutex — khóa loại trừ tương hỗ',
  'critical section': 'vùng tới hạn',
  'race condition': 'điều kiện tranh chấp',
  'deadlock': 'bế tắc (deadlock)',
  'atomic': 'nguyên tử (atomic)',
  'assembly': 'hợp ngữ',
  'instruction': 'lệnh máy',
  'opcode': 'mã lệnh',
  'address': 'địa chỉ',
  'offset': 'độ lệch địa chỉ',
  'base address': 'địa chỉ cơ sở',
  'pointer': 'con trỏ',
  'alignment': 'căn chỉnh địa chỉ/bộ nhớ',
  'cache': 'bộ nhớ đệm (cache)',
  'cache coherency': 'tính nhất quán của bộ nhớ đệm',
  'pipeline': 'đường ống xử lý lệnh (pipeline)',
  'exception': 'ngoại lệ',
  'fault': 'lỗi ngoại lệ (fault)',
  'hard fault': 'ngoại lệ HardFault',
  'halt': 'dừng thực thi',
  'breakpoint': 'điểm dừng gỡ lỗi',
  'debug': 'gỡ lỗi',
  'jtag': 'JTAG — giao tiếp kiểm thử/gỡ lỗi',
  'swd': 'SWD — giao tiếp gỡ lỗi nối tiếp',
  'reference manual': 'tài liệu tham chiếu kỹ thuật',
  'datasheet': 'tài liệu thông số kỹ thuật',
};

export function normalizeSelection(text) {
  return String(text).replace(/\r\n?/g, '\n').replace(/\u00ad/g, '').replace(/([a-z])-\n[ \t]*([a-z])/g, '$1$2')
    .split('\n').map(line => {
      const indent = line.match(/^[ \t]*/)[0];
      return indent.replace(/\t/g, '  ') + line.slice(indent.length).replace(/[ \t]+/g, ' ').trimEnd();
    }).join('\n').trim();
}
export function lookupTerm(text) {
  return glossary[normalizeSelection(text).replace(/\s+/g, ' ').toLowerCase().replace(/[.,;:]$/, '')] ?? null;
}
export function relevantTerms(text) {
  const lower = text.toLowerCase().replace(/\s+/g, ' ');
  return Object.entries(glossary).filter(([term]) => {
    const escaped = term.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    return new RegExp(`(?<![a-z0-9_])${escaped}(?![a-z0-9_])`, 'i').test(lower);
  }).sort((a, b) => b[0].length - a[0].length).slice(0, 24);
}
